@cmdbwebhooks2kafka_HostAddress = http://localhost:5080

GET {{cmdbwebhooks2kafka_HostAddress}}/health
Accept: application/json

###

POST {{cmdbwebhooks2kafka_HostAddress}}/webhooks/cmdbuild
Content-Type: application/json
Authorization: Bearer dev-cmdb-webhook-token

{
  "source": "cmdbuild",
  "eventType": "update",
  "cmdbuildEvent": "card_update_after",
  "className": "Notebook",
  "id": "97805",
  "code": "2222",
  "ip_address": "192.168.10.10",
  "description": "qq1"
}
