<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>cmdbwebhooks2kafka</AssemblyName>
    <RootNamespace>CmdbWebhooks2Kafka</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.14.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../shared/Logging/*.cs" Link="Logging/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Http/*.cs" Link="Http/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Kafka/*.cs" Link="Kafka/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Metrics/*.cs" Link="Metrics/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Security/*.cs" Link="Security/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Secrets/*.cs" Link="Secrets/%(Filename)%(Extension)" />
    <Compile Include="../shared/State/*.cs" Link="State/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Transport/*.cs" Link="Transport/Shared/%(Filename)%(Extension)" />
    <Compile Include="../shared/Workers/*.cs" Link="Workers/Shared/%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
